#!/bin/bash

cd build
cmake -DCMAKE_TOOLCHAIN_FILE=../android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=9 \
 -DANDROID_STL=gnustl_static \
 -DTARGET_PLATFORM="Android" \
 -DBUILD_GL_RENDER=OFF -DBUILD_GLSL_RENDER=OFF -DBUILD_GLES_RENDER=ON ../../../
cd ..

